_format_version: "3.0"
_transform: true

# Kong Gateway Configuration for BLOASIS
# gRPC-to-REST transcoding via grpc-gateway plugin
# Proto files are mounted at /kong/proto/ from shared/proto/

# =============================================================================
# JWT Consumer Configuration (RS256)
# =============================================================================
# JWT consumers are used to verify JWT tokens using RS256 algorithm
# The public key is extracted from the Auth Service's RSA key pair
# Private key stays in Auth Service, public key is distributed to Kong

consumers:
  - username: bloasis-jwt-consumer
    custom_id: jwt-auth-consumer
    jwt_secrets:
      - key: bloasis-jwt-issuer
        algorithm: RS256
        # RSA public key for token verification
        # Generate using: ./scripts/generate_jwt_keys.sh
        # Then copy contents of infra/keys/jwt-public.pem here
        # IMPORTANT: In production, use environment variable or Kong Admin API
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          REPLACE_WITH_PUBLIC_KEY_CONTENTS
          -----END PUBLIC KEY-----

# =============================================================================
# Services Configuration
# =============================================================================

services:
  # Market Regime Service (Tier 1 - shared data)
  # Provides market regime classification (crisis, bear, bull, sideways, recovery)
  # Cached for 6 hours, shared across ALL users
  - name: market-regime-service
    url: grpc://market-regime:50051
    routes:
      - name: market-regime-route
        paths:
          - /v1/market-regime
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/market_regime.proto

  # Portfolio Service (user-specific data)
  # Provides portfolio summary and position management
  # User-specific data with 1-hour cache TTL
  # Note: Write operations (UpdateCashBalance, CreatePosition, etc.) are internal-only (no HTTP annotations)
  # PROTECTED: Requires JWT authentication
  - name: portfolio-service
    url: grpc://portfolio:50057
    routes:
      - name: portfolio-route
        paths:
          - /v1/portfolio
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/portfolio.proto
      - name: jwt
        config:
          key_claim_name: sub
          claims_to_verify:
            - exp
          # RS256 uses asymmetric keys (public key for verification)
      - name: request-transformer
        config:
          add:
            headers:
              - "X-User-Id:$(jwt.claims.sub)"

  # Market Data Service (Tier 1 - shared data)
  # Provides stock market data (OHLCV, metadata) via yfinance
  # Cached for 5 minutes to balance freshness with API rate limits
  - name: market-data-service
    url: grpc://market-data:50053
    routes:
      - name: market-data-route
        paths:
          - /v1/market-data
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/market_data.proto

  # Notification WebSocket Service
  # Provides real-time notifications via WebSocket
  # WebSocket Upgrade headers are passed through Kong
  - name: notification-ws
    url: http://notification:8000
    routes:
      - name: notification-ws-route
        paths:
          - /ws
        protocols:
          - http
          - https
        strip_path: false

  # =============================================================================
  # Protected Services (JWT Required)
  # =============================================================================
  # The following services require JWT authentication (RS256)
  # JWT token must be provided in Authorization header: Bearer <token>
  # After validation, X-User-Id header is set from JWT sub claim

  # Strategy Service (user-specific strategies)
  # Provides strategy recommendations and customization
  # PROTECTED: Requires JWT authentication
  - name: strategy-service
    url: grpc://strategy:50054
    routes:
      - name: strategy-route
        paths:
          - /v1/strategy
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/strategy.proto
      - name: jwt
        config:
          key_claim_name: sub
          claims_to_verify:
            - exp
          # RS256 uses asymmetric keys (public key for verification)
      - name: request-transformer
        config:
          add:
            headers:
              - "X-User-Id:$(jwt.claims.sub)"

  # Executor Service (trade execution)
  # Provides order execution via Alpaca paper trading
  # PROTECTED: Requires JWT authentication
  - name: executor-service
    url: grpc://executor:50058
    routes:
      - name: executor-route
        paths:
          - /v1/executor
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/executor.proto
      - name: jwt
        config:
          key_claim_name: sub
          claims_to_verify:
            - exp
          # RS256 uses asymmetric keys (public key for verification)
      - name: request-transformer
        config:
          add:
            headers:
              - "X-User-Id:$(jwt.claims.sub)"

  # =============================================================================
  # Public Services (No Authentication Required)
  # =============================================================================
  # The following services are publicly accessible without JWT

  # Auth Service (authentication endpoints)
  # Provides login and token refresh functionality
  # PUBLIC: No JWT required (users authenticate here to get JWT)
  - name: auth-service
    url: grpc://auth:50060
    routes:
      - name: auth-route
        paths:
          - /v1/auth
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/auth.proto
      # No JWT plugin - public endpoint for login/refresh

# Add services as they are implemented
# See services/CLAUDE.md for gRPC service setup
