_format_version: "3.0"
_transform: true

# Kong Gateway Configuration for BLOASIS
# gRPC-to-REST transcoding via grpc-gateway plugin
# Proto files are mounted at /kong/proto/ from shared/proto/

services:
  # Market Regime Service (Tier 1 - shared data)
  # Provides market regime classification (crisis, bear, bull, sideways, recovery)
  # Cached for 6 hours, shared across ALL users
  - name: market-regime-service
    url: grpc://market-regime:50051
    routes:
      - name: market-regime-route
        paths:
          - /v1/market-regime
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/market_regime.proto

  # Portfolio Service (user-specific data)
  # Provides portfolio summary and position management
  # User-specific data with 1-hour cache TTL
  # Note: Write operations (UpdateCashBalance, CreatePosition, etc.) are internal-only (no HTTP annotations)
  - name: portfolio-service
    url: grpc://portfolio:50057
    routes:
      - name: portfolio-route
        paths:
          - /v1/portfolio
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/portfolio.proto

  # Market Data Service (Tier 1 - shared data)
  # Provides stock market data (OHLCV, metadata) via yfinance
  # Cached for 5 minutes to balance freshness with API rate limits
  - name: market-data-service
    url: grpc://market-data:50053
    routes:
      - name: market-data-route
        paths:
          - /v1/market-data
        protocols:
          - http
          - https
    plugins:
      - name: grpc-gateway
        config:
          proto: /kong/proto/market_data.proto

# Add services as they are implemented
# See services/CLAUDE.md for gRPC service setup
