.PHONY: proto-generate proto-lint proto-check test lint check

# Proto related
proto-generate:
	cd shared/proto && buf generate
	echo "# Generated proto files - auto-generated by buf generate" > shared/generated/__init__.py

proto-lint:
	cd shared/proto && buf lint

proto-check: proto-lint
	cd shared/proto && buf generate

# Testing (uv manages PYTHONPATH via pyproject.toml)
test:
	uv run pytest --cov --cov-fail-under=80

# Lint
lint:
	uv run ruff check shared/ services/

# Full verification
check: lint proto-lint test
